# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentralSite',
            fields=[
                ('address', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 1, 14, 13, 15, 23, 403590, tzinfo=utc), verbose_name='date published')),
                ('rent', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('distance_km', models.FloatField(default=0, verbose_name='distance')),
                ('duration_minutes', models.FloatField(default=0, verbose_name='time')),
                ('type', models.CharField(default='Unknown', max_length=50)),
                ('deliveriesPerMonth', models.IntegerField(default=0)),
                ('costPerKm', models.FloatField(default=0, verbose_name='time')),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_app.CentralSite')),
            ],
        ),
        migrations.CreateModel(
            name='TransportClasses',
            fields=[
                ('transport', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('costPerKm', models.FloatField(default=0, verbose_name='distance')),
            ],
        ),
    ]
