# Generated by Django 2.2 on 2019-05-06 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentralSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 5, 6, 14, 51, 12, 716985, tzinfo=utc), verbose_name='date published')),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('user', models.CharField(max_length=50)),
                ('costPerMonth', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransportClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(max_length=200)),
                ('costPerKm', models.FloatField(default=0, verbose_name='distance')),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=50)),
                ('distance_km', models.FloatField(default=0, verbose_name='distance')),
                ('duration_minutes', models.FloatField(default=0, verbose_name='time')),
                ('type', models.CharField(default='Unknown', max_length=50)),
                ('deliveriesPerMonth', models.FloatField(default=0)),
                ('routeCost', models.FloatField(default=0, verbose_name='time')),
                ('routeCostPerMonth', models.FloatField(default=0, verbose_name='time')),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_app.CentralSite')),
            ],
        ),
    ]
