# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0005_auto_20180114_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='routeCostPerMonth',
            field=models.FloatField(default=0, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='centralsite',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 14, 16, 5, 6, 315304, tzinfo=utc), verbose_name='date published'),
        ),
    ]
