# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 17:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0006_auto_20180114_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralsite',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 17, 52, 6, 41852, tzinfo=utc), verbose_name='date published'),
        ),
    ]
