# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0007_auto_20180119_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralsite',
            name='rent',
        ),
        migrations.AlterField(
            model_name='centralsite',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 20, 12, 43, 36, 576458, tzinfo=utc), verbose_name='date published'),
        ),
    ]
