# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0008_auto_20180120_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralsite',
            name='costPerMonth',
            field=models.FloatField(default=0, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='centralsite',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 20, 13, 7, 57, 448731, tzinfo=utc), verbose_name='date published'),
        ),
    ]
