# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 13:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0010_auto_20180120_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralsite',
            name='costPerMonth',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='centralsite',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 20, 13, 24, 36, 207741, tzinfo=utc), verbose_name='date published'),
        ),
    ]
