# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0011_auto_20180120_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralsite',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 16, 21, 6, 104445, tzinfo=utc), verbose_name='date published'),
        ),
    ]
