# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0012_auto_20180131_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralsite',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 19, 32, 19, 717314, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='route',
            name='deliveriesPerMonth',
            field=models.FloatField(default=0),
        ),
    ]
