# Generated by Django 2.0.3 on 2018-04-03 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0013_auto_20180131_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralsite',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 19, 3, 20, 222514, tzinfo=utc), verbose_name='date published'),
        ),
    ]
